# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on: [push]

jobs:
  build:
    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.21
        uses: actions/setup-node@v1
        with:
          node-version: 12.21
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint:ci
      - name: Build
        run: npm run build:ci
      - name: Test
        run: npm run test:ci
      - name: E2E
        run: npm run e2e:ci
