module.exports = {
  projects: [
    '<rootDir>/apps/api',
    '<rootDir>/apps/fullerstack',
    '<rootDir>/libs/ngx-config',
    '<rootDir>/libs/ngx-logger',
    '<rootDir>/libs/ngx-subify',
    '<rootDir>/libs/nsx-prisma',
    '<rootDir>/libs/nsx-user',
    '<rootDir>/libs/nsx-common',
    '<rootDir>/libs/nsx-auth',
    '<rootDir>/libs/agx-util',
    '<rootDir>/libs/ngx-jwt',
    '<rootDir>/libs/ngx-menu',
    '<rootDir>/libs/ngx-i18n',
    '<rootDir>/libs/ngx-gtag',
    '<rootDir>/libs/ngx-msg',
    '<rootDir>/libs/ngx-material',
    '<rootDir>/libs/agx-assets',
    '<rootDir>/libs/ngx-layout',
  ],
};
