# Used for login and registration
mutation JwtLogin($email: String!, $password: String!) {
  jwtLogin(email: $email, password: $password) {
    ok
    msg
    errno
    token
  }
}

# Used for login and registration
mutation JwtRegister(
  $firstName: String!
  $lastName: String
  $language: String
  $email: String!
  $password: String!
) {
  jwtRegister(
    firstName: $firstName
    lastName: $lastName
    language: $language
    email: $email
    password: $password
  ) {
    ok
    msg
    errno
    token
  }
}

# Used prior to token expiry
mutation JwtRefresh($token: String!) {
  jwtRefresh(token: $token) {
    ok
    msg
    errno
    token
  }
}
